### ISSUE TITLE
Decide how to organize repository

### ISSUE THREAD

**Issue by rccreswell** [pints-team/bayesian-differential-equations-db#1]
Simple models whose implementation amounts to no more than a simple subclass of pints.ForwardModel and whose data size is small are easy to accumulate.

It is less clear to me how best to organize within the repository more complex models which include e.g., nontrivial dependencies, extension modules, and large datasets. It seems advantageous that such models be separately installable with their own setup.py, so the uninterested user need not bother with them. Thus, my current plan is to add the hydrology model as an independent package in its own directory within pints-models. However, this structure makes `pip install git ...` more difficult and seems somewhat nonstandard. 

I wonder if this is something you thought about @ben18785 ?

**Comment by MichaelClerx** [comment]
Just weighing in :D 

Subdirectories would be fine, you'd just have to tell users to go to the subdirectory of choice, and only then pip install!

Other options might be having lots of repos and one repo that's just a link

Or even one repo with a list in its main/master branch, and branches for all other things. That's my least favourite of the three :D

**Comment by rccreswell** [comment]
Thanks @MichaelClerx , I'll try the subdirectories then. It should be easy enough to switch to your second suggestion if that becomes necessary.
