### ISSUE TITLE
Name of repo

### ISSUE THREAD

**Issue by ben18785** [pints-team/bayesian-differential-equations-db#4]
Thanks for setting up @rcw5890 -- looks great. One thought: I was hoping we could make this repo as discoverable as possible for PINTS-outsiders. So, I was wondering whether we might want to call it something like:

1. differential-equation-database
2. bayesian-differential-equation-db

I'd advocate for something like the latter perhaps. What do you think?

**Comment by rccreswell** [comment]
Bayesian differential equation sounds good to me.

**Comment by ben18785** [comment]
Cool. I've changed the repo name to it.
